apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "bankingdb"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  SPRING_PROFILES_ACTIVE: "prod"
